#!/usr/bin/env bash
# Installing and configuring HAproxy on  lb-01 server.

# Updating packages
sudo apt update

# Adding HAProxy PPA
sudo apt install -y software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt update

# Installing  HAProxy
sudo apt install -y haproxy=1.8.\*

hgproxy_conf_file="/etc/haproxy/haproxy.cfg"

# Configuring the  Load Balancer
fname="frontend http"
fbind="bind *:80"
fmode="mode http"
fdefault="default_backend web-backend"
frontend="$fname\n\t$fbind\n\t$fmode\n\t$fdefault\n"

bname="backend web-backend"
bbalance="balance roundrobin"
bserver1="server 134417-web-01 18.234.253.166 check"
bserver2="server 134417-web-02 100.26.175.54 check"
backend="$bname\n\t$bbalance\n\t$bserver1\n\t$bserver2"

sudo sed -i "$ a $frontend" $hgproxy_conf_file
sudo sed -i "$ a $backend" $hgproxy_conf_file

# Restart HAProxy service
sudo service haproxy restart
